[project]
name = "projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cvzone>=1.6.1",
    "filterpy>=1.4.5",
    "opencv-python>=4.13.0.92",
    "ultralytics>=8.4.14",
]
